apiVersion: v1
kind: Service
metadata:
  name: {{ include "exchangedb.fullname" . }}
  labels:
    {{- include "exchangedb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.postgresql }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
    - port: {{ .Values.service.ports.ilp }}
      targetPort: ilp
      protocol: TCP
      name: ilp
  selector:
    {{- include "exchangedb.selectorLabels" . | nindent 4 }}
